/**
 *
 * $Id$
 */
package hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.validation;

import hu.bme.mit.inf.modes3.components.safetylogic.systemlevel.model.RailRoadModel.Path;

import hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.RouteElement;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
	boolean validate();

	boolean validatePaths(EList<Path> value);

	boolean validateFirst(RouteElement value);

	boolean validateLast(RouteElement value);
}
