/**
 *
 * $Id$
 */
package hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.validation;

import hu.bme.mit.inf.modes3.components.safetylogic.systemlevel.model.RailRoadModel.Train;

import hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.ScheduleSection;
import hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.Station;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.ScheduleEntry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScheduleEntryValidator {
	boolean validate();

	boolean validateSections(EList<ScheduleSection> value);
	boolean validateFrom(Station value);
	boolean validateTo(Station value);
	boolean validateTrain(Train value);

	boolean validateFirst(ScheduleSection value);

	boolean validateLast(ScheduleSection value);
}
