/**
 *
 * $Id$
 */
package hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.validation;

import hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.Route;

import hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.ScheduleSection;
import java.util.Date;

/**
 * A sample validator interface for {@link hu.bme.mit.inf.modes3.components.scheduler.model.SchedulerModel.ScheduleSection}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ScheduleSectionValidator {
	boolean validate();

	boolean validateSupposedDeparture(Date value);
	boolean validateActualDeparture(Date value);
	boolean validateRoute(Route value);

	boolean validateNext(ScheduleSection value);

	boolean validatePrevious(ScheduleSection value);
}
